discourse_onedrive_picker:
  discourse_onedrive_picker_enabled:
    default: true
    client: true
  discourse_onedrive_picker_azure_client_id:
    default: ''
    client: true
  discourse_onedrive_picker_site_base_url:
    default: ''
    client: true
